import axios from 'axios';

export const FETCH_ALL_TICKETS = "FETCH_ALL_TICKETS"
export const POST_NEW_TICKET = "POST_NEW_TICKET"
export const DELETE_TICKET_DATA = "DELETE_TICKET_DATA"
export const UPDATE_TICKET_DATA = "UPDATE_TICKET_DATA"
export const HELP_TICKET_DATA = "HELP_TICKET_DATA"
export const UNHELP_TICKET_DATA = "UNHELP_TICKET_DATA"
export const FETCH_RESOLVED_TICKET = "FETCH_RESOLVED_TICKET"
export const FETCH_UNRESOLVED_TICKET = "FETCH_UNRESOLVED_TICKET"
export const LOGIN = "LOGIN"
export const LOGOUT = "LOGOUT"
export const POST_REGISTRATION = "POST_REGISTRATION"